In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'text':['people watch me',' me watch me','people write comment','me write comment'],'output':[1,1,0,0]})

In [3]:
df

,text,output
0,people watch me,1
1,me watch me,1
2,people write comment,0
3,me write comment,0


In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv=CountVectorizer(ngram_range=(2,2))

In [6]:
bow=cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)

{'people watch': 2, 'watch me': 4, 'me watch': 0, 'people write': 3, 'write comment': 5, 'me write': 1}


In [8]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


In [9]:
cv.transform(["me watch and write comment of me"]).toarray()

array([[1, 0, 0, 0, 0, 1]])

#### class sklearn.feature_extraction.text.CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)[source]


In [10]:
### binary=True then all non-zero count =1.  jaha bhi 2 ya 3 or or bds number uss ko 1 bna dega.. iss me ham freq nhi ptakrte iss me pta lrte hai ke exist krta hauke nhi

### binary=True then all non-zero count =1.  jaha bhi 2 ya 3 or or bda number uss ko 1 bna dega.. iss me ham freq nhi pta krte iss me pta krte hai ke exist krta hai ke nhi

In [11]:
###

### max_features=1 then is ka matlab hai ke ek hi featiure output me chayea jis ke frequency sb se jada hai or baki ignore ho jai ge words